# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /inhouse
COPY ./requirements.txt /requirements.txt
RUN pip install -r requirements.txt
COPY ./inhouse /inhouse

WORKDIR /inhouse
EXPOSE 8000

