version: '3.5'


services:
  app:
    build: .
    command: python ./inhouse/manage.py runserver 0.0.0.0:8000
    volumes:
      - static_data:/static
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./inhouse/.env
    depends_on:
      - app-db

  app-db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB:csbldb
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:orange
      - TZ:America/New_York

volumes:
  static_data:
  postgres_data:

  