version: '3.5'


services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./inhouse/.env

volumes:
  static:

  