# Generated by Django 4.0.2 on 2022-02-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(to='users.Topic'),
        ),
    ]
