# Generated by Django 4.0.3 on 2022-04-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_topic_user_user_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.TextField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='classStanding',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personalBio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
