# Generated by Django 4.0.3 on 2022-04-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_classstanding_user_classstanding_user_personalbio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classStanding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.classstanding'),
        ),
    ]
