# Generated by Django 4.0.1 on 2022-03-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_remove_reservation_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="feedback",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
