version: '3.5'


services:
  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_data:/static
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    networks:
      - djangonetwork
    depends_on:
      - app-db
    links:
      - app-db:app-db

  app-db:
    build: .
    image: postgres:12-alpine
    container_name: app-db
    ports:
      - "5432:5432"
    networks:
      - djangonetwork
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env

volumes:
  static_data:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge

  