version: '3.5'


services:
  app:
    build:
      context: .
    volumes:
      - static_data:/static
    ports:
      - "80:8000"
    restart: always
    env_file:
      - .env
    networks:
      - djangonetwork
    depends_on:
      - app-db
    links:
      - app-db:app-db
    command: gunicorn inhouse.wsgi:application -w 2 -b :8000

  app-db:
    image: postgres:12-alpine
    container_name: app-db
    ports:
      - "5432:5432"
    networks:
      - djangonetwork
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  static_data:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge

  