# Generated by Django 4.0.2 on 2022-02-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardmanlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsession',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
