# Generated by Django 4.0.2 on 2022-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardmanlab", "0004_helpsession_is_inperson_helpsession_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpsession",
            name="remote_link",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
