# Generated by Django 4.0.2 on 2022-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardmanlab", "0008_alter_helpsession_is_inperson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpsession",
            name="notes",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="helpsession",
            name="remote_link",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
